export const WORDS = [
  "FLOWERS", "FLOWER", "LOWER", "ROWER", "SOWER", "SLOW", "FLOW", "WOLF", "ROLE", "ROSE", "SORE", "LOSE", "LESS", "SEER", "FEEL", "FLEE", "FREE", "REEL", "ELSE", "SELF", "SERF", "ORES", "LOWS", "ROWS", "OWLS", "FOES", "WOES", "EELS", "REFS", "FEW", "SEE", "FEE", "LOW", "ROW", "SOW",
  "GARDENS", "GARDEN", "RAGE", "GEAR", "NEAR", "READ", "DEAR", "DARE", "SAND", "SEND", "SEAR", "EARS", "AGES", "SAGE", "SANG", "SNAG", "DRAG", "DREG", "NAGS", "RAGS", "DANS", "EARN", "DEAN", "DANG", "GANG", "GEES", "GENE", "SEEN", "SEED", "NEED", "DENS", "ENDS", "RAG", "RAN", "SAD", "SEA",
  "PROJECT", "OBJECT", "CORE", "CROP", "COPE", "PORE", "PORT", "ROPE", "POET", "COTE", "TORE", "ROTE", "REPO", "PERT", "CREPT", "CROP", "JET", "JOB", "JOG", "JOT", "JOY", "ORE", "POT", "PET", "OPT", "TOP", "ROT", "TOE", "COT", "COP",
  "KITCHEN", "THICK", "NICHE", "CHIN", "INCH", "TECH", "ETCH", "HINT", "THIN", "TINE", "KITE", "HIKE", "TICK", "NECK", "NICE", "THEN", "THEE", "HEN", "HIT", "KIN", "KIT", "NET", "NIT", "TEN", "TIE", "TIN", "INK", "ICE",
  "MORNING", "MORN", "RING", "GRIN", "IRON", "NORM", "GROIN", "MINOR", "NON", "GIN", "RIM", "RIG", "NOR", "ION", "INN",
  "JOURNAL", "OUR", "JAR", "URN", "RUN", "OAR", "ORAL", "ROAN", "LOAN", "LORN", "LUNA", "JURA", "JARL",
  "FRIENDS", "FRIEND", "FIEND", "FENDS", "DRIES", "FRIES", "SIRED", "RIFES", "REINS", "RESIN", "RINSE", "RISEN", "SIREN", "DINER", "FINDS", "FIRES", "NERDS", "SENDS", "SINEW", "WINES", "WIRES", "WRENS", "DINE", "DIRE", "DINS", "ENDS", "FENS", "FERN", "FIND", "FINE", "FINS", "FIRE", "FIRS", "FRED", "IDES", "IRES", "NERD", "REDS", "REFS", "REIF", "REIN", "REND", "RIBS", "RIDE", "RIDS", "RIFE", "RIFS", "RIGS", "RIND", "RINS", "RISE", "SEND", "SERF", "SIDE", "SINE", "SIRE", "WEDS", "WEIR", "WIDE", "WIFE", "WIND", "WINE", "WING", "WIRE", "WISE", "WISH", "WREN",
  "VIOLETS", "VIOLET", "VOILE", "TOILS", "TILES", "STOVE", "SOLVE", "OLIVES", "LOVES", "LIVES", "LISTS", "ISLES", "VEST", "VETS", "VEIL", "TOIL", "TILE", "SOIL", "SLOT", "SILO", "LOVE", "LIVE", "LIST", "LEST", "EVIL", "OILS", "LIT", "LOT", "SET", "SIT", "SOT", "TIE", "TOE", "VET", "VIE",
  "PUMPKIN", "PUMP", "PINK", "PUNK", "PLUM", "KILN", "LINK", "MINK", "MILK", "PUN", "PIN", "INK", "KIN", "NIL", "LIP",
  "ALCOHOL", "COOL", "HALL", "COAL", "COLA", "HALO", "LOCO", "HOLL", "ALL", "COO", "HAL",
  "NETWORK", "WORK", "WONT", "WORE", "WORT", "KNOW", "KNOT", "NEWT", "NOTE", "TONE", "TOWN", "TOKE", "TEWN", "TEN", "TOE", "TON", "TOW", "TWO", "WON", "NOT", "NET", "NEW", "NOW",
  "HAMSTER", "HARM", "HARE", "HATE", "HEAR", "HEAT", "HEMS", "HERS", "MARE", "MARS", "MART", "MASH", "MAST", "MATE", "MATH", "MATS", "MEAT", "MESH", "METH", "RARE", "RASH", "RATE", "RATS", "REAM", "REAR", "REST", "RHEA", "SAME", "SEAM", "SEAR", "SEAT", "SERA", "SHAM", "SHEA", "STAR", "STEM", "TAME", "TAMS", "TARE", "TARS", "TEAM", "TEAR", "TEAS", "TERM", "THEM", "TRAM", "ART", "ASH", "ATE", "EAR", "EAT", "ERA", "HAM", "HAS", "HAT", "HEM", "HER", "HES", "MAR", "MAS", "MAT", "MET", "RAM", "RAT", "RES", "SAT", "SEA", "SET", "SHE", "TAM", "TAR", "TEA", "THE",
  "EXPLORE", "REPEL", "PEER", "REEL", "ROLE", "ROPE", "POLE", "PORE", "LORE", "EEL", "LEE", "LOP", "ORE", "PER", "POL", "PRO", "REP", "ROE",
  "SHELTER", "SHEET", "STEEL", "STEER", "THERE", "THREE", "TREE", "HEEL", "HERE", "LEER", "LEST", "REEL", "REST", "SEER", "ELSE", "HER", "LET", "SEE", "SET", "SHE", "TEE", "THE",
  "CRYSTAL", "CART", "CAST", "CATS", "CLAY", "RATS", "RAYS", "SALT", "SCAR", "SCAT", "SLAT", "SLAY", "STAR", "STAY", "TARS", "TRAY", "ACT", "ALT", "ARC", "ART", "ASH", "ASK", "CAT", "CRY", "HAS", "HAT", "HAY", "LAY", "RAT", "RAY", "SAY", "SHY", "SKY", "SLY", "STY", "TAR", "TRY",
  "POULTRY", "POLY", "PORT", "POUR", "POUT", "PURL", "ROPY", "ROUT", "RULE", "TORY", "TOUR", "TOY", "TOP", "POT", "LOT", "ROT", "PUT", "OUT", "OUR", "YOU",
  "BLANKET", "ABLE", "BALE", "BALK", "BANK", "BEAK", "BEAN", "BEAT", "BELT", "BENT", "BETA", "KALE", "LAKE", "LAMB", "LANE", "LANK", "LATE", "LEAK", "LEAN", "LENT", "NEAT", "TALE", "TALK", "TANK", "TEAK", "ALB", "ALT", "ANT", "ATE", "BAN", "BAT", "BET", "EAT", "ELK", "LAB", "LEA", "LET", "NAB", "NET", "TAB", "TAN", "TEA", "TEN"
];
